server:
  port: 8181

spring:
  application:
    name: account-service
  zipkin:
    base-url: http://localhost:9411/
  boot:
    admin:
      client:
        url: http://localhost:8184

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

springcloud:
  cassandra:
    contact:
      point: localhost
    port: 9042
    keyspace:
      name: springCloud
    username: cassandra
    password: cassandra

