server:
  port: 8183

spring:
  application:
    name: notification-service
  rabbitmq:
    username: semarslan
    password: semarslan
  cloud:
    stream:
      bindings:
        input:
          destination: msqueue
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

