server:
  port: 8183

spring:
  application:
    name: notification-service
  rabbitmq:
    username: semarslan
    password: semarslan
  boot:
    admin:
      client:
        url: http://localhost:8184
  cloud:
    stream:
      bindings:
        input:
          destination: msqueue
  zipkin:
    base-url: http://localhost:9411/

management:
  endpoints:
    web:
      exposure:
      include: "*"


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

