server:
  port: 8181

spring:
  application:
    name: account-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/


springcloud:
  cassandra:
    contact:
      point: localhost
    port: 9042
    keyspace:
      name: springCloud
    username: cassandra
    password: cassandra