version: '3.1'

services:
  cassandra:
    image: cassandra:latest
    ports:
      - 9042:9042

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  elasticsearch:
    image: elasticsearch:7.10.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node